### ISSUE TITLE
Error when using this plugin

### ISSUE THREAD

**Issue by marcj** [christopherthielen/typedoc-plugin-external-module-name#308]
After installing `typedoc-plugin-external-module-name` in devDependencies and executing `typedoc -v` I get this:

```
Error: The plugin /Users/marc/bude/glut.ts/node_modules/typedoc-plugin-external-module-name could not be loaded.

Error: Cannot find module 'typedoc/dist/lib/models/reflections/abstract'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/marc/bude/glut.ts/node_modules/typedoc-plugin-external-module-name/plugin.js:18:24
    at /Users/marc/bude/glut.ts/node_modules/typedoc-plugin-external-module-name/plugin.js:9:17
    at Object.<anonymous> (/Users/marc/bude/glut.ts/node_modules/typedoc-plugin-external-module-name/plugin.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)

TypeDoc 0.14.2
Using TypeScript 3.2.4 from /usr/local/lib/node_modules/typedoc/node_modules/typescript/lib
```

**Comment by marcj** [comment]
Ok got it, you have to install "typedoc" in your package as well, not globally.
