### ISSUE TITLE
typedoc-plugin-folder-modules is not working

### ISSUE THREAD

**Issue by rohitghy5** [christopherthielen/typedoc-plugin-external-module-name#311]
Plugin typedoc-plugin-folder-modules is not working and giving below error:

admin@localhost typedoc]$ typedoc --options typedocconfig.ts --plugin "typedoc-plugin-folder-modules"
Error: The plugin typedoc-plugin-folder-modules could not be loaded.

TypeError: Class constructor ConverterComponent cannot be invoked without 'new'
    at new FolderModulesPlugin (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc-plugin-folder-modules/plugin.js:43:46)
    at Converter.addComponent (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc/dist/lib/utils/component.js:123:19)
    at Converter.addComponent (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc/dist/lib/converter/converter.js:28:33)
    at module.exports (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc-plugin-folder-modules/index.js:4:17)
    at PluginHost.load (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc/dist/lib/utils/plugins.js:36:21)
    at CliApplication.bootstrap (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc/dist/lib/application.js:42:22)
    at CliApplication.bootstrap (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc/dist/lib/cli.js:24:30)
    at new Application (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc/dist/lib/application.js:31:14)
    at new CliApplication (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc/dist/lib/cli.js:22:1)
    at Object.<anonymous> (/home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typedoc/bin/typedoc:4:1)

Using TypeScript 3.2.2 from /home/admin/node-v8.11.4-linux-x64/lib/node_modules/npm/node_modules/typescript/lib
Rendering [====================================----] 88%
Error: Documentation could not be generated due to the errors above.

**Comment by christopherthielen** [comment]
I think you filed this issue in the wrong repository.    Maybe you meant to file this in https://github.com/bort2012/typedoc-plugin-folder-modules ?
