### ISSUE TITLE
Issue with TypeScript 2.0.6

### ISSUE THREAD

**Issue by unsafecode** [christopherthielen/typedoc-plugin-external-module-name#4]
I'm facing this issue using `typedoc@0.5.1`, `typescript@2.0.6` and `node@6.9.2` on Windows 10

```
typedoc "--options" "typedoc.json" "--exclude" "'**/*.spec.ts'" "./src/"

Loaded plugin typedoc-plugin-external-module-name

Using TypeScript 2.0.6 from C:\Users\XXXXX\node_modules\typedoc\node_modules\typescript\lib

C:\Users\XXXX\node_modules\typedoc-plugin-external-module-name\node_modules\typedoc\dist\lib\converter\factories\comment.js:47
    var comments = _ts.getJSDocCommentRanges(node, sourceFile.text);
                                                             ^

TypeError: Cannot read property 'text' of undefined
    at Object.getRawComment (C:\Users\XXXXX\node_modules\typedoc-plugin-external-module-name\node_modules\typedoc\dist\lib\converter\factories\comment.js:47:62)
    at ExternalModuleNamePlugin.onDeclaration (C:\Users\XXXXX\node_modules\typedoc-plugin-external-module-name\plugin.js:82:41)
    at triggerEvents (C:\Users\XXXXX\node_modules\typedoc\lib\utils\events.js:129:43)
    at triggerApi (C:\Users\XXXXX\node_modules\typedoc\lib\utils\events.js:106:13)
    at eventsApi (C:\Users\XXXXX\node_modules\typedoc\lib\utils\events.js:20:18)
    at Converter.EventDispatcher.trigger (C:\Users\XXXXX\node_modules\typedoc\lib\utils\events.js:261:13)
    at Context.trigger (C:\Users\XXXXX\node_modules\typedoc\lib\converter\context.js:56:24)
    at Object.createDeclaration (C:\Users\XXXXX\node_modules\typedoc\lib\converter\factories\declaration.js:85:17)
    at C:\Users\XXXXX\node_modules\typedoc\lib\converter\nodes\block.js:53:34
    at Context.withSourceFile (C:\Users\XXXXX\node_modules\typedoc\lib\converter\context.js:79:9)
```
typedoc.json

```json
{
  "mode": "modules",
  "out": "doc",
  "theme": "default",
  "ignoreCompilerErrors": "true",
  "experimentalDecorators": "true",
  "emitDecoratorMetadata": "true",
  "target": "ES5",
  "moduleResolution": "node",
  "preserveConstEnums": "true",
  "stripInternal": "true",
  "suppressExcessPropertyErrors": "true",
  "suppressImplicitAnyIndexErrors": "true",
  "module": "commonjs"
}
```

Removing the plugin solves it and the docs are correctly rendered.

**Comment by christopherthielen** [comment]
I was able to reproduce the error.  The error went away after updating to typedoc 0.5.3 and above.

**Comment by christopherthielen** [comment]
Hmm, seems there are two different versions being used and they are not compatible.  Might be a problem with the plugin's `typedoc` dependency...

<img width="447" alt="screen shot 2017-01-17 at 9 26 55 am" src="https://cloud.githubusercontent.com/assets/2053478/22026709/3c22171a-dc97-11e6-91fe-30684f205d6e.png">

<img width="444" alt="screen shot 2017-01-17 at 9 27 01 am" src="https://cloud.githubusercontent.com/assets/2053478/22026719/3f1a66ac-dc97-11e6-8789-950647ab6c00.png">

**Comment by christopherthielen** [comment]
I switched from 
```
dependencies: {
  typedoc: "^0.5.3"
}
```

to

```
peerDependencies: {
  typedoc: "^0.5.3"
}
```

The plugin requires typedoc 0.5.3 and above.  In 0.5.3 some exported symbols (which the plugin requires) were moved.
